[Main]
debug_level     = info
;libspdm_log    = 1      ; enable libspdm log output
;doe_log        = 1      ; enable DOE log

[Ports]
rootport_1      = 02.0   ; dev/func of rootport 1
endpoint_1      = 00.0   ; dev/func of endpoint 1

[Topology_1]
type            = link_ide        ; Link IDE
connection      = direct          ; Directly connected EP
bus             = 0x1f
path1           = rootport_1,endpoint_1
stream_id       = 0

[Configuration_1]
type            = link_ide
category        = soc-cxl

[TestSuite_1]
type                    = link_ide
category                = soc-cxl
configuration           = 1
topology                = 1
IdeCapabilityStructure  = 1
